development:
  adapter: postgresql
  database: mall_recipes_development
  host: localhost
  pool: 5
  timeout: 5000
test:
  adapter: postgresql
  host: localhost
  database: mall_recipes_test
  pool: 5
  timeout: 5000

production:
  url: <%= ENV['DATABASE_URL'] %>
  adapter: postgresql
  host: 
  database: mall_recipes_production
  pool: 5
  timeout: 5000
